name: Manual pull request

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3

      - name: Create .env file
        run: |
          touch .env
          echo -e "AIRTABLE_API_KEY=${{ secrets.AIRTABLE_API_KEY }}" >> .env
          echo -e "AIRTABLE_BASE_ID=${{ secrets.AIRTABLE_BASE_ID }}" >> .env
          echo -e "ALGOLIA_ADMIN_API_KEY=${{ secrets.ALGOLIA_ADMIN_API_KEY }}" >> .env
          echo -e "GATSBY_ALGOLIA_APP_ID=${{ secrets.GATSBY_ALGOLIA_APP_ID }}" >> .env
          echo -e "GATSBY_ALGOLIA_INDEX_NAME=${{ secrets.GATSBY_ALGOLIA_INDEX_NAME }}" >> .env
          echo -e "GATSBY_ALGOLIA_SEARCH_API_KEY=${{ secrets.GATSBY_ALGOLIA_SEARCH_API_KEY }}" >> .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-engines

      - run: yarn clean
      - run: yarn typegen
      - run: yarn export:smarthr_ui

      - name: craete pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Update build files'
